# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='LOW', max_length=6)),
                ('created_by', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.CharField(max_length=64)),
                ('closed_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
