# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_ticket_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
