# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20181019_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
