# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20181019_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
