# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
